language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: precise
    - dist: trusty
    - dist: xenial
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode9.4
    - os: osx
      brew_packages: curl
      env: PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
    - os: osx
      brew_packages: curl-openssl
      env: PKG_CONFIG_PATH="/usr/local/opt/curl-openssl/lib/pkgconfig"
    - os: osx
      before_install:
        - brew install curl --HEAD
        - brew link --force curl
      env: PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      r: 3.5.3

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
