language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

before_install:
  - mkdir -p ~/.R/Makevars
  - echo "CFLAGS = -g -O2 -Wall -Wno-unused -pedantic" >> ~/.R/Makevars

r_github_packages:
  - jimhester/covr
  - hadley/httr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
